version: '3'

dotenv:
  - .env

tasks:
  start:
    desc: Запустить API
    # deps: [compose:local]
    cmds:
      - >
        uv run uvicorn
        --reload
        --host $HOST
        --port $PORT
        "$APP_MODULE"

  uv:install:main:
    desc: Установить только основные зависимости (без dev)
    cmds:
      - uv sync --no-dev

  uv:install:all:
    desc: Установить все зависимости
    cmds:
      - uv sync

  postgres:db:
    desc: БД без сохранения volumes, для разработки и тестов
    cmds:
      - >
        docker run --name=interwiews_db
        -e SSL_MODE=disable
        -e POSTGRES_USER=$PG_USER
        -e POSTGRES_PASSWORD=$PG_PASSWORD
        -e POSTGRES_DB=$PG_DB
        -e TZ=GMT-3
        -p $PG_PORT:5432
        -d --rm
        postgres:17.0-alpine3.19

  postgres:db:volume:
    desc: БД с volume (данные сохраняются при удалении контейнера)
    cmds:
      - >
        docker run --name=interwiews_db
        -e SSL_MODE=disable
        -e POSTGRES_USER=$PG_USER
        -e POSTGRES_PASSWORD=$PG_PASSWORD
        -e POSTGRES_DB=$PG_DB
        -e TZ=GMT-3
        -v interwiews_db_data:/var/lib/postgresql/data
        -p $PG_PORT:5432
        -d --rm
        postgres:17.0-alpine3.19

  postgres:stop:
    desc: Остановить БД
    cmds:
      - docker stop interwiews_db

  redis:up:
    desc: Запустить Redis
    cmds:
      - docker run --name=redis_db -p 6379:6379 -d --rm redis


  alembic:revision:
    desc: Создать ревизию alembic
    cmds:
      - uv run alembic revision --autogenerate -m "{{.CLI_ARGS}}"

  alembic:migrate:
    desc: Провести миграцию БД до последней ревизии
    cmds:
      -  uv run alembic upgrade head

  seed:load:
    desc: Загрузить сиды в БД
    cmds:
      - python seed/main.py

  compose:local:
    desc: Поднять локальный compose (для разработки)
    cmds:
      - docker compose -f docker-compose.local.yml up -d || true

  compose:produp:
    desc: Поднять прод compose
    cmds:
      - docker compose up -d --build
