"""initial

Revision ID: 927a29683009
Revises: 
Create Date: 2026-03-09 02:33:52.145292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '927a29683009'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_update', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conducted_by', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['conducted_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('audio_path', sa.String(length=256), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('date_create', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_update', sa.DateTime(timezone=True), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('interview_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('analysis',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('recomendation', sa.Text(), nullable=True),
    sa.Column('answer_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis')
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('interviews')
    op.drop_table('plans')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
